### ISSUE TITLE
Implement as Treeprocessor

### ISSUE THREAD

**Issue by ProgramFan** [ProgramFan/asciidoctor-bibtex#5]
As the asciidoctor-mathematical inline stem suggests, it is possible to implement the inline cite or citenp using a Treeprocessor. This enables the following features:

1. cite macros can cross then multiple lines.
2. attributes are then be parsed correctly and directly by asciidoctor.

**Comment by ProgramFan** [comment]
Maybe we shall move asciidoc to asciidoc support into a seperate class, to make the code cleaner.

**Comment by ProgramFan** [comment]
@mojavelinux, How can I create an ordered list or an unordered list and replace the corrent block with the generated content in a treeprocessor? I have tried several approaches but no success yet.

**Comment by ProgramFan** [comment]
Solved. `Asciidoctor::Extension::parse_content` can construct an AST from any content. So I can generated required asciidoc conent and use parse_content to generate blocks. To replace current block with new blocks, operate directly on  `block.parent.blocks`.

**Comment by mojavelinux** [comment]
That's indeed one way to do it. You can also construct the nodes using the API. It's best to look at the core parser to see how it's done.

* https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/parser.rb#L1144
* https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/parser.rb#L1288

Obviously you don't need to do the parsing...just create the `:ulist` block and add child `ListItem` objects to it. If you need a simple example, I can try to put one together.

**Comment by ProgramFan** [comment]
Thanks, @mojavelinux. I experimented with the idea and it works well.

**Comment by ProgramFan** [comment]
BTW. Is it possible for this extension to become part of asciidoctor.org? @mojavelinux

**Comment by mojavelinux** [comment]
>  I experimented with the idea and it works well.

Great!

>  Is it possible for this extension to become part of asciidoctor.org? 

Indeed. That would be wonderful! I think it will be less confusing for people if we disassociate from the asciidoc-bib fork. It will also give us more freedom to take it in our own direction. We can certainly reference asciidoc-bib in the README and explain that this extension was inspired by that one. But I don't think that we are a fork in the GitHub definition of the term.

Do you foresee the project supporting other bibliography schemas, or will it remain focused on bibtex? I ask because if it's the former, we might consider naming it asciidoctor-bibliography (similar to asciidoctor-diagram). But only if that's the case.

**Comment by ProgramFan** [comment]
It is of course possible for this project to support other bibliography schemas. But since bibtex is used so widely in the scientific community, I would like to focus on bibtex and make it perfect. Focusing on bibtex also makes it easy to integrate with the latex toolchain, which is the de-facto standard in scientific publication.

One problem we may face when disassociating from the asciidoc-bib fork is the licence. asciidoc-bib is licenced under OpenWorks licence, which makes me doub if we can safely disassociate from the original package, since this extension reuses a lot of its code. Anyway, this extension is quite different from asciidoc-bib, and we can contact the original author if disassociation is necessary.

**Comment by ProgramFan** [comment]
I checked the OpenWorks licence, it has almost no restrictions, given the licence itself is included somewhere in the software. So I will take your suggestion and brand this extension as "inspired by asciidoc-bib".

By the way, I have made a transfer request for this extension to be part of asciidoctor.org. Would you please check it? @mojavelinux

**Comment by ProgramFan** [comment]
Hi, @mojavelinux, I have transfered the repo to asciidoctor.org but lost all administration rights (see #12 ). Would you please help restore it? Thanks a lot.

**Comment by mojavelinux** [comment]
> since bibtex is used so widely in the scientific community, I would like to focus on bibtex and make it perfect

Sounds good to me! I was asking in order to understand how best to choose a name for the project. Since the focus will remain on bibtex, I think we should keep the current name.

> which makes me doub if we can safely disassociate from the original package

When I say "disassociate", I merely mean removing the upstream link on GitHub. That is unrelated to licensing compliance as it's specific to the GitHub UI.

> we can contact the original author if disassociation is necessary.

We have every right to make that decision ourselves.

**Comment by mojavelinux** [comment]
I've asked GitHub to remove the fork status.
